---
title: "Check"
author: "[hachiman_oct](https://github.com/hachiman-oct)"
date: today
format:
  html:
    toc: true
    toc_float: false 
    toc-depth: 4
    toc-expand: 2
    css:  
      - https://cdn.jsdelivr.net/gh/hachiman-oct/resources@main/qmd/darkmode.css
      - https://cdn.jsdelivr.net/gh/hachiman-oct/resources@main/qmd/toc-right-toggle.css
---

# MCQ Check

```{=html}
<button id="toc-toggle">☰ TOC</button>
<script src="https://cdn.jsdelivr.net/gh/hachiman-oct/resources@main/qmd/toc-right-toggle.js"></script>
```

## Business_Law

## Management_Accounting

### 原価管理とは
|          |                    |                    | 備考 |
|----------|----------|----------|--------------------------------------------|
| 原価管理 | 原価計画<br>(原価低減) | 原価企画,<br>原価改善 | 原価計算基準が規定する原価管理には含まない |
|          | 原価統制           | 原価維持           ||

### 製造間接費の部門別計算
#### 部門費の1次集計
- 原価管理の見地から近年は部門個別費と部門共通費の区別をなくし，すべて部門個別費として把握する動向が見られる

#### 複数配賦基準法
- 複数配賦基準法のもとでは，純理論的には相互配賦法の採用が前提

### 個別原価計算
- 予算操業度は期待実際操業度や短期予定操業度と同義と捉えてよい

### 副産物
販管費の見積額は控除しない

### フリーキャッシュフロー
$$
\sum^{\infty} ar^{n} = \frac{ar}{1-r}
$$
$$
r = \frac{1}{1+b}
$$
$$
\therefore\frac{ar}{1-r} = \frac{a}{b}
$$


NOPAT = 営業利益 * (1-税率)

FCF = NOPAT + Dep - 正味運転資本増加額 - 設備投資額



### EVA
経済的付加価値は営業利益から税額と資本コストの額を控除するが，この場合の税額は，有利子負債コストの節税効果は反映されていない

CC = 期首投下資本 * 加重平均資本コスト

EVA = NOPAT - CC


## Auditing


## Financial_Accounting

### 投資その他の資産の具体例

|   | 意義 |
|:------------------------:|----------------------------------------------|
| 投資有価証券 | 流動資産に属しない有価証券 |
| 関係会社株式 |  |
| 出資金 | 協同組合，匿名組合等への出資持分 |
| 長期貸付金 | １年以内に返済期日が到来しない貸付金 |
| 破産更生債権等 | 破産債権，再生債権，更生債権その他これらに準ずる債権で一年以内に回収が見込まれないもの |
| 長期前払費用 | 前払費用のうち，１年以内に費用とならないもの |
| 投資不動産 | 投資目的で所有する土地，建物その他の不動産 |
| 長期性預金 | 期間が１年を超える預金で，１年以内に期限の到来しない預金 |

### 有価証券の分類

|  |  |
|:----------------------:|------------------------------------------------|
| 流動資産 | ・売買目的有価証券<br>・１年以内に処分されると認められる親会社株式<br>・１年内に満期の到来する社債その他の債券 |
| 固定資産<br>(投資その他の資産) | 上記以外の有価証券 |

※親会社株式は，その保有目的に従い，売買目的有価証券又はその他有価証券に分類する．したがって，時価をもって貸借対照表価額とし，評価差額をそれぞれの保有目的区分に係る方法に準拠して処理する．そして，貸借対照表日後１年以内に処分されると認められるものは，流動資産に「親会社株式」の科目をもって別に掲記しなければならない．他方，貸借対照表日後１年以内に処分されると認められるもの以外のものは，投資その他の資産に「親会社株式」の科目をもって別に掲記しなければならない．ただし，その金額が僅少である場合には注記によることができる．

### 減価償却の基礎知識

-   遊休資産も減価償却を行う
-   有形固定資産の減価償却費は「販売費及び一般管理費」
-   有形固定資産の使用開始時から減価償却を行う（取得時からではない）

### 株主資本

#### 分配可能額

分配可能額 = 剰余金 - 分配時における自己株式- 自己株式の処分の対価 - 前期B/Sその他有価証券(negative) - 前期B/S分配制限額

#### 準備金の積立額

分配制限額(> 0) = max{$\frac{のれん}{2}$ - (資本金 + 準備金), その他資本剰余金} + 繰延資産